"""Report endpoints — trends, campaigns, reps, CSV/PDF export."""

import csv
import io
from datetime import datetime, date

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from database import get_db, User
from dependencies import get_current_user, get_call_scope_filter, require_supervisor_or_admin
from models.schemas import TrendBucket, CampaignStats, RepStats
from services.reports import (
    compute_trends, compute_campaigns, compute_reps, get_calls_for_export,
)

router = APIRouter(prefix="/api/reports", tags=["reports"])


def _parse_date(d: str | None) -> date | None:
    if not d:
        return None
    try:
        return datetime.strptime(d, "%Y-%m-%d").date()
    except ValueError:
        raise HTTPException(status_code=400, detail=f"Invalid date format: {d}. Use YYYY-MM-DD.")


@router.get("/trends")
def trends_report(
    period: str = Query("weekly", pattern="^(weekly|monthly)$"),
    start_date: str | None = Query(None),
    end_date: str | None = Query(None),
    rep_id: int | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    scope_filter=Depends(get_call_scope_filter),
):
    sd = _parse_date(start_date)
    ed = _parse_date(end_date)
    return compute_trends(db, scope_filter, current_user, period, sd, ed, rep_id)


@router.get("/campaigns", response_model=list[CampaignStats])
def campaigns_report(
    start_date: str | None = Query(None),
    end_date: str | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    scope_filter=Depends(get_call_scope_filter),
):
    sd = _parse_date(start_date)
    ed = _parse_date(end_date)
    return compute_campaigns(db, scope_filter, sd, ed)


@router.get("/reps", response_model=list[RepStats])
def reps_report(
    start_date: str | None = Query(None),
    end_date: str | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_supervisor_or_admin),
    scope_filter=Depends(get_call_scope_filter),
):
    sd = _parse_date(start_date)
    ed = _parse_date(end_date)
    return compute_reps(db, scope_filter, sd, ed)


@router.get("/export/csv")
def export_csv(
    start_date: str | None = Query(None),
    end_date: str | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    scope_filter=Depends(get_call_scope_filter),
):
    sd = _parse_date(start_date)
    ed = _parse_date(end_date)

    output = io.StringIO()
    writer = csv.writer(output)

    rows = get_calls_for_export(db, scope_filter, sd, ed)
    if rows:
        writer.writerow(rows[0].keys())
        for row in rows:
            writer.writerow(row.values())
    else:
        writer.writerow(["No data"])

    output.seek(0)
    today = datetime.now().strftime("%Y-%m-%d")
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=calls-export-{today}.csv"},
    )


@router.get("/export/pdf")
def export_pdf(
    start_date: str | None = Query(None),
    end_date: str | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    scope_filter=Depends(get_call_scope_filter),
):
    sd = _parse_date(start_date)
    ed = _parse_date(end_date)

    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("CTM Scorer — Calls Report", styles["Title"]))
    date_range = f"{sd or 'All time'} to {ed or 'today'}"
    elements.append(Paragraph(f"Date range: {date_range} | Generated by: {current_user.name}", styles["Normal"]))
    elements.append(Spacer(1, 20))

    rows = get_calls_for_export(db, scope_filter, sd, ed)
    if rows:
        headers = ["Date", "Campaign", "Keyword", "Rep", "Rep Score", "Lead Score", "Conversion"]
        table_data = [headers]
        for r in rows:
            table_data.append([
                r["call_date"], r["campaign"], r["keyword"],
                r["rep"], str(r["rep_score"]), str(r["lead_score"]),
                r["conversion"],
            ])
    else:
        table_data = [["No data"]]

    table = Table(table_data)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4338ca")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    footer = datetime.now().strftime("Generated %Y-%m-%d %H:%M UTC")
    elements.append(Paragraph(footer, styles["Normal"]))

    doc.build(elements)
    buffer.seek(0)

    today = datetime.now().strftime("%Y-%m-%d")
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=calls-report-{today}.pdf"},
    )
